/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_Evil */

#ifndef _Included_hello_Evil
#define _Included_hello_Evil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_Evil
 * Method:    readTLABPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Evil_readTLABPointer(JNIEnv *env, jclass klass) {
  jlong addr;
  asm("movq 0x60(%%r15), %0;":"=r"(addr)::);
  return addr;
}

#ifdef __cplusplus
}
#endif
#endif
